// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ExpectationServiceCreateResponse expectation service create response
//
// swagger:model ExpectationServiceCreateResponse
type ExpectationServiceCreateResponse struct {

	// success
	// Example: true
	Success bool `json:"success,omitempty"`
}

// Validate validates this expectation service create response
func (m *ExpectationServiceCreateResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this expectation service create response based on context it is used
func (m *ExpectationServiceCreateResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ExpectationServiceCreateResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExpectationServiceCreateResponse) UnmarshalBinary(b []byte) error {
	var res ExpectationServiceCreateResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
