// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ExpectationServiceDeleteResponse expectation service delete response
//
// swagger:model ExpectationServiceDeleteResponse
type ExpectationServiceDeleteResponse struct {

	// success
	// Example: true
	Success bool `json:"success,omitempty"`
}

// Validate validates this expectation service delete response
func (m *ExpectationServiceDeleteResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this expectation service delete response based on context it is used
func (m *ExpectationServiceDeleteResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ExpectationServiceDeleteResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExpectationServiceDeleteResponse) UnmarshalBinary(b []byte) error {
	var res ExpectationServiceDeleteResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
