// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RouteServiceDeleteRequest route service delete request
//
// swagger:model RouteServiceDeleteRequest
type RouteServiceDeleteRequest struct {

	// Server name is a unique identifier of the mock server.
	// Example: http-server-8080
	// Required: true
	// Min Length: 1
	ServerName *string `json:"server_name"`

	// URL is a relative URI of the route.
	// Example: /some-url
	// Required: true
	// Min Length: 1
	URL *string `json:"url"`
}

// Validate validates this route service delete request
func (m *RouteServiceDeleteRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateServerName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateURL(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RouteServiceDeleteRequest) validateServerName(formats strfmt.Registry) error {

	if err := validate.Required("server_name", "body", m.ServerName); err != nil {
		return err
	}

	if err := validate.MinLength("server_name", "body", *m.ServerName, 1); err != nil {
		return err
	}

	return nil
}

func (m *RouteServiceDeleteRequest) validateURL(formats strfmt.Registry) error {

	if err := validate.Required("url", "body", m.URL); err != nil {
		return err
	}

	if err := validate.MinLength("url", "body", *m.URL, 1); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this route service delete request based on context it is used
func (m *RouteServiceDeleteRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RouteServiceDeleteRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RouteServiceDeleteRequest) UnmarshalBinary(b []byte) error {
	var res RouteServiceDeleteRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
