// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ServerServiceStartResponse server service start response
//
// swagger:model ServerServiceStartResponse
type ServerServiceStartResponse struct {

	// address
	// Example: 127.0.0.1:8080
	// Min Length: 1
	Address string `json:"address,omitempty"`

	// success
	// Example: true
	Success bool `json:"success,omitempty"`
}

// Validate validates this server service start response
func (m *ServerServiceStartResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAddress(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ServerServiceStartResponse) validateAddress(formats strfmt.Registry) error {
	if swag.IsZero(m.Address) { // not required
		return nil
	}

	if err := validate.MinLength("address", "body", m.Address, 1); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this server service start response based on context it is used
func (m *ServerServiceStartResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServerServiceStartResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServerServiceStartResponse) UnmarshalBinary(b []byte) error {
	var res ServerServiceStartResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
