// Code generated by go-swagger; DO NOT EDIT.

package route_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/status-mok/server/e2e/app/http-client/models"
)

// NewRouteServiceCreateParams creates a new RouteServiceCreateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRouteServiceCreateParams() *RouteServiceCreateParams {
	return &RouteServiceCreateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRouteServiceCreateParamsWithTimeout creates a new RouteServiceCreateParams object
// with the ability to set a timeout on a request.
func NewRouteServiceCreateParamsWithTimeout(timeout time.Duration) *RouteServiceCreateParams {
	return &RouteServiceCreateParams{
		timeout: timeout,
	}
}

// NewRouteServiceCreateParamsWithContext creates a new RouteServiceCreateParams object
// with the ability to set a context for a request.
func NewRouteServiceCreateParamsWithContext(ctx context.Context) *RouteServiceCreateParams {
	return &RouteServiceCreateParams{
		Context: ctx,
	}
}

// NewRouteServiceCreateParamsWithHTTPClient creates a new RouteServiceCreateParams object
// with the ability to set a custom HTTPClient for a request.
func NewRouteServiceCreateParamsWithHTTPClient(client *http.Client) *RouteServiceCreateParams {
	return &RouteServiceCreateParams{
		HTTPClient: client,
	}
}

/*
RouteServiceCreateParams contains all the parameters to send to the API endpoint

	for the route service create operation.

	Typically these are written to a http.Request.
*/
type RouteServiceCreateParams struct {

	// Body.
	Body *models.RouteServiceCreateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the route service create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RouteServiceCreateParams) WithDefaults() *RouteServiceCreateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the route service create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RouteServiceCreateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the route service create params
func (o *RouteServiceCreateParams) WithTimeout(timeout time.Duration) *RouteServiceCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the route service create params
func (o *RouteServiceCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the route service create params
func (o *RouteServiceCreateParams) WithContext(ctx context.Context) *RouteServiceCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the route service create params
func (o *RouteServiceCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the route service create params
func (o *RouteServiceCreateParams) WithHTTPClient(client *http.Client) *RouteServiceCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the route service create params
func (o *RouteServiceCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the route service create params
func (o *RouteServiceCreateParams) WithBody(body *models.RouteServiceCreateRequest) *RouteServiceCreateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the route service create params
func (o *RouteServiceCreateParams) SetBody(body *models.RouteServiceCreateRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *RouteServiceCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
