// Code generated by go-swagger; DO NOT EDIT.

package route_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/status-mok/server/e2e/app/http-client/models"
)

// RouteServiceCreateReader is a Reader for the RouteServiceCreate structure.
type RouteServiceCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RouteServiceCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRouteServiceCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewRouteServiceCreateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRouteServiceCreateOK creates a RouteServiceCreateOK with default headers values
func NewRouteServiceCreateOK() *RouteServiceCreateOK {
	return &RouteServiceCreateOK{}
}

/*
RouteServiceCreateOK describes a response with status code 200, with default header values.

A successful response.
*/
type RouteServiceCreateOK struct {
	Payload *models.RouteServiceCreateResponse
}

// IsSuccess returns true when this route service create o k response has a 2xx status code
func (o *RouteServiceCreateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this route service create o k response has a 3xx status code
func (o *RouteServiceCreateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this route service create o k response has a 4xx status code
func (o *RouteServiceCreateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this route service create o k response has a 5xx status code
func (o *RouteServiceCreateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this route service create o k response a status code equal to that given
func (o *RouteServiceCreateOK) IsCode(code int) bool {
	return code == 200
}

func (o *RouteServiceCreateOK) Error() string {
	return fmt.Sprintf("[POST /route/create][%d] routeServiceCreateOK  %+v", 200, o.Payload)
}

func (o *RouteServiceCreateOK) String() string {
	return fmt.Sprintf("[POST /route/create][%d] routeServiceCreateOK  %+v", 200, o.Payload)
}

func (o *RouteServiceCreateOK) GetPayload() *models.RouteServiceCreateResponse {
	return o.Payload
}

func (o *RouteServiceCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RouteServiceCreateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRouteServiceCreateDefault creates a RouteServiceCreateDefault with default headers values
func NewRouteServiceCreateDefault(code int) *RouteServiceCreateDefault {
	return &RouteServiceCreateDefault{
		_statusCode: code,
	}
}

/*
RouteServiceCreateDefault describes a response with status code -1, with default header values.

RouteServiceCreateDefault route service create default
*/
type RouteServiceCreateDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// Code gets the status code for the route service create default response
func (o *RouteServiceCreateDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this route service create default response has a 2xx status code
func (o *RouteServiceCreateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this route service create default response has a 3xx status code
func (o *RouteServiceCreateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this route service create default response has a 4xx status code
func (o *RouteServiceCreateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this route service create default response has a 5xx status code
func (o *RouteServiceCreateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this route service create default response a status code equal to that given
func (o *RouteServiceCreateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *RouteServiceCreateDefault) Error() string {
	return fmt.Sprintf("[POST /route/create][%d] RouteService_Create default  %+v", o._statusCode, o.Payload)
}

func (o *RouteServiceCreateDefault) String() string {
	return fmt.Sprintf("[POST /route/create][%d] RouteService_Create default  %+v", o._statusCode, o.Payload)
}

func (o *RouteServiceCreateDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *RouteServiceCreateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
