// Code generated by go-swagger; DO NOT EDIT.

package server_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/status-mok/server/e2e/app/http-client/models"
)

// NewServerServiceStartParams creates a new ServerServiceStartParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewServerServiceStartParams() *ServerServiceStartParams {
	return &ServerServiceStartParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewServerServiceStartParamsWithTimeout creates a new ServerServiceStartParams object
// with the ability to set a timeout on a request.
func NewServerServiceStartParamsWithTimeout(timeout time.Duration) *ServerServiceStartParams {
	return &ServerServiceStartParams{
		timeout: timeout,
	}
}

// NewServerServiceStartParamsWithContext creates a new ServerServiceStartParams object
// with the ability to set a context for a request.
func NewServerServiceStartParamsWithContext(ctx context.Context) *ServerServiceStartParams {
	return &ServerServiceStartParams{
		Context: ctx,
	}
}

// NewServerServiceStartParamsWithHTTPClient creates a new ServerServiceStartParams object
// with the ability to set a custom HTTPClient for a request.
func NewServerServiceStartParamsWithHTTPClient(client *http.Client) *ServerServiceStartParams {
	return &ServerServiceStartParams{
		HTTPClient: client,
	}
}

/*
ServerServiceStartParams contains all the parameters to send to the API endpoint

	for the server service start operation.

	Typically these are written to a http.Request.
*/
type ServerServiceStartParams struct {

	// Body.
	Body *models.ServerServiceStartRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the server service start params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ServerServiceStartParams) WithDefaults() *ServerServiceStartParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the server service start params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ServerServiceStartParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the server service start params
func (o *ServerServiceStartParams) WithTimeout(timeout time.Duration) *ServerServiceStartParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the server service start params
func (o *ServerServiceStartParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the server service start params
func (o *ServerServiceStartParams) WithContext(ctx context.Context) *ServerServiceStartParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the server service start params
func (o *ServerServiceStartParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the server service start params
func (o *ServerServiceStartParams) WithHTTPClient(client *http.Client) *ServerServiceStartParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the server service start params
func (o *ServerServiceStartParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the server service start params
func (o *ServerServiceStartParams) WithBody(body *models.ServerServiceStartRequest) *ServerServiceStartParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the server service start params
func (o *ServerServiceStartParams) SetBody(body *models.ServerServiceStartRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ServerServiceStartParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
