// Code generated by go-swagger; DO NOT EDIT.

package server_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/status-mok/server/e2e/app/http-client/models"
)

// ServerServiceStopReader is a Reader for the ServerServiceStop structure.
type ServerServiceStopReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ServerServiceStopReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewServerServiceStopOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewServerServiceStopDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewServerServiceStopOK creates a ServerServiceStopOK with default headers values
func NewServerServiceStopOK() *ServerServiceStopOK {
	return &ServerServiceStopOK{}
}

/*
ServerServiceStopOK describes a response with status code 200, with default header values.

A successful response.
*/
type ServerServiceStopOK struct {
	Payload *models.ServerServiceStopResponse
}

// IsSuccess returns true when this server service stop o k response has a 2xx status code
func (o *ServerServiceStopOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this server service stop o k response has a 3xx status code
func (o *ServerServiceStopOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this server service stop o k response has a 4xx status code
func (o *ServerServiceStopOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this server service stop o k response has a 5xx status code
func (o *ServerServiceStopOK) IsServerError() bool {
	return false
}

// IsCode returns true when this server service stop o k response a status code equal to that given
func (o *ServerServiceStopOK) IsCode(code int) bool {
	return code == 200
}

func (o *ServerServiceStopOK) Error() string {
	return fmt.Sprintf("[POST /server/stop][%d] serverServiceStopOK  %+v", 200, o.Payload)
}

func (o *ServerServiceStopOK) String() string {
	return fmt.Sprintf("[POST /server/stop][%d] serverServiceStopOK  %+v", 200, o.Payload)
}

func (o *ServerServiceStopOK) GetPayload() *models.ServerServiceStopResponse {
	return o.Payload
}

func (o *ServerServiceStopOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServerServiceStopResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewServerServiceStopDefault creates a ServerServiceStopDefault with default headers values
func NewServerServiceStopDefault(code int) *ServerServiceStopDefault {
	return &ServerServiceStopDefault{
		_statusCode: code,
	}
}

/*
ServerServiceStopDefault describes a response with status code -1, with default header values.

ServerServiceStopDefault server service stop default
*/
type ServerServiceStopDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// Code gets the status code for the server service stop default response
func (o *ServerServiceStopDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this server service stop default response has a 2xx status code
func (o *ServerServiceStopDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this server service stop default response has a 3xx status code
func (o *ServerServiceStopDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this server service stop default response has a 4xx status code
func (o *ServerServiceStopDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this server service stop default response has a 5xx status code
func (o *ServerServiceStopDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this server service stop default response a status code equal to that given
func (o *ServerServiceStopDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ServerServiceStopDefault) Error() string {
	return fmt.Sprintf("[POST /server/stop][%d] ServerService_Stop default  %+v", o._statusCode, o.Payload)
}

func (o *ServerServiceStopDefault) String() string {
	return fmt.Sprintf("[POST /server/stop][%d] ServerService_Stop default  %+v", o._statusCode, o.Payload)
}

func (o *ServerServiceStopDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *ServerServiceStopDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
