// Code generated by go-swagger; DO NOT EDIT.

package server_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/status-mok/server/e2e/app/http-client/models"
)

// NewServerServiceStopParams creates a new ServerServiceStopParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewServerServiceStopParams() *ServerServiceStopParams {
	return &ServerServiceStopParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewServerServiceStopParamsWithTimeout creates a new ServerServiceStopParams object
// with the ability to set a timeout on a request.
func NewServerServiceStopParamsWithTimeout(timeout time.Duration) *ServerServiceStopParams {
	return &ServerServiceStopParams{
		timeout: timeout,
	}
}

// NewServerServiceStopParamsWithContext creates a new ServerServiceStopParams object
// with the ability to set a context for a request.
func NewServerServiceStopParamsWithContext(ctx context.Context) *ServerServiceStopParams {
	return &ServerServiceStopParams{
		Context: ctx,
	}
}

// NewServerServiceStopParamsWithHTTPClient creates a new ServerServiceStopParams object
// with the ability to set a custom HTTPClient for a request.
func NewServerServiceStopParamsWithHTTPClient(client *http.Client) *ServerServiceStopParams {
	return &ServerServiceStopParams{
		HTTPClient: client,
	}
}

/*
ServerServiceStopParams contains all the parameters to send to the API endpoint

	for the server service stop operation.

	Typically these are written to a http.Request.
*/
type ServerServiceStopParams struct {

	// Body.
	Body *models.ServerServiceStopRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the server service stop params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ServerServiceStopParams) WithDefaults() *ServerServiceStopParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the server service stop params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ServerServiceStopParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the server service stop params
func (o *ServerServiceStopParams) WithTimeout(timeout time.Duration) *ServerServiceStopParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the server service stop params
func (o *ServerServiceStopParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the server service stop params
func (o *ServerServiceStopParams) WithContext(ctx context.Context) *ServerServiceStopParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the server service stop params
func (o *ServerServiceStopParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the server service stop params
func (o *ServerServiceStopParams) WithHTTPClient(client *http.Client) *ServerServiceStopParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the server service stop params
func (o *ServerServiceStopParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the server service stop params
func (o *ServerServiceStopParams) WithBody(body *models.ServerServiceStopRequest) *ServerServiceStopParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the server service stop params
func (o *ServerServiceStopParams) SetBody(body *models.ServerServiceStopRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ServerServiceStopParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
