// Code generated by go-swagger; DO NOT EDIT.

package server_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/status-mok/server/e2e/app/http-client/models"
)

// NewServerServiceCreateParams creates a new ServerServiceCreateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewServerServiceCreateParams() *ServerServiceCreateParams {
	return &ServerServiceCreateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewServerServiceCreateParamsWithTimeout creates a new ServerServiceCreateParams object
// with the ability to set a timeout on a request.
func NewServerServiceCreateParamsWithTimeout(timeout time.Duration) *ServerServiceCreateParams {
	return &ServerServiceCreateParams{
		timeout: timeout,
	}
}

// NewServerServiceCreateParamsWithContext creates a new ServerServiceCreateParams object
// with the ability to set a context for a request.
func NewServerServiceCreateParamsWithContext(ctx context.Context) *ServerServiceCreateParams {
	return &ServerServiceCreateParams{
		Context: ctx,
	}
}

// NewServerServiceCreateParamsWithHTTPClient creates a new ServerServiceCreateParams object
// with the ability to set a custom HTTPClient for a request.
func NewServerServiceCreateParamsWithHTTPClient(client *http.Client) *ServerServiceCreateParams {
	return &ServerServiceCreateParams{
		HTTPClient: client,
	}
}

/*
ServerServiceCreateParams contains all the parameters to send to the API endpoint

	for the server service create operation.

	Typically these are written to a http.Request.
*/
type ServerServiceCreateParams struct {

	// Body.
	Body *models.ServerServiceCreateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the server service create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ServerServiceCreateParams) WithDefaults() *ServerServiceCreateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the server service create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ServerServiceCreateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the server service create params
func (o *ServerServiceCreateParams) WithTimeout(timeout time.Duration) *ServerServiceCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the server service create params
func (o *ServerServiceCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the server service create params
func (o *ServerServiceCreateParams) WithContext(ctx context.Context) *ServerServiceCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the server service create params
func (o *ServerServiceCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the server service create params
func (o *ServerServiceCreateParams) WithHTTPClient(client *http.Client) *ServerServiceCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the server service create params
func (o *ServerServiceCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the server service create params
func (o *ServerServiceCreateParams) WithBody(body *models.ServerServiceCreateRequest) *ServerServiceCreateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the server service create params
func (o *ServerServiceCreateParams) SetBody(body *models.ServerServiceCreateRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ServerServiceCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
