// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mok "github.com/status-mok/server/internal/mok"
	mock "github.com/stretchr/testify/mock"
)

// StorageMock is an autogenerated mock type for the StorageMock type
type StorageMock struct {
	mock.Mock
}

// ServerCreate provides a mock function with given fields: ctx, srv
func (_m *StorageMock) ServerCreate(ctx context.Context, srv mok.Server) error {
	ret := _m.Called(ctx, srv)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, mok.Server) error); ok {
		r0 = rf(ctx, srv)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerDelete provides a mock function with given fields: ctx, name
func (_m *StorageMock) ServerDelete(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerGet provides a mock function with given fields: ctx, name
func (_m *StorageMock) ServerGet(ctx context.Context, name string) (mok.Server, error) {
	ret := _m.Called(ctx, name)

	var r0 mok.Server
	if rf, ok := ret.Get(0).(func(context.Context, string) mok.Server); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mok.Server)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewStorageMock interface {
	mock.TestingT
	Cleanup(func())
}

// NewStorageMock creates a new instance of StorageMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStorageMock(t mockConstructorTestingTNewStorageMock) *StorageMock {
	mock := &StorageMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
