// Code generated by go-swagger; DO NOT EDIT.

package expectation_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new expectation service API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for expectation service API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	ExpectationServiceCreate(params *ExpectationServiceCreateParams, opts ...ClientOption) (*ExpectationServiceCreateOK, error)

	ExpectationServiceDelete(params *ExpectationServiceDeleteParams, opts ...ClientOption) (*ExpectationServiceDeleteOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
ExpectationServiceCreate creates
*/
func (a *Client) ExpectationServiceCreate(params *ExpectationServiceCreateParams, opts ...ClientOption) (*ExpectationServiceCreateOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewExpectationServiceCreateParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ExpectationService_Create",
		Method:             "POST",
		PathPattern:        "/expectation/create",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ExpectationServiceCreateReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ExpectationServiceCreateOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ExpectationServiceCreateDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
ExpectationServiceDelete deletes
*/
func (a *Client) ExpectationServiceDelete(params *ExpectationServiceDeleteParams, opts ...ClientOption) (*ExpectationServiceDeleteOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewExpectationServiceDeleteParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ExpectationService_Delete",
		Method:             "POST",
		PathPattern:        "/expectation/delete",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ExpectationServiceDeleteReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ExpectationServiceDeleteOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ExpectationServiceDeleteDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
