// Code generated by go-swagger; DO NOT EDIT.

package expectation_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/status-mok/server/e2e/app/http-client/models"
)

// NewExpectationServiceDeleteParams creates a new ExpectationServiceDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewExpectationServiceDeleteParams() *ExpectationServiceDeleteParams {
	return &ExpectationServiceDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewExpectationServiceDeleteParamsWithTimeout creates a new ExpectationServiceDeleteParams object
// with the ability to set a timeout on a request.
func NewExpectationServiceDeleteParamsWithTimeout(timeout time.Duration) *ExpectationServiceDeleteParams {
	return &ExpectationServiceDeleteParams{
		timeout: timeout,
	}
}

// NewExpectationServiceDeleteParamsWithContext creates a new ExpectationServiceDeleteParams object
// with the ability to set a context for a request.
func NewExpectationServiceDeleteParamsWithContext(ctx context.Context) *ExpectationServiceDeleteParams {
	return &ExpectationServiceDeleteParams{
		Context: ctx,
	}
}

// NewExpectationServiceDeleteParamsWithHTTPClient creates a new ExpectationServiceDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewExpectationServiceDeleteParamsWithHTTPClient(client *http.Client) *ExpectationServiceDeleteParams {
	return &ExpectationServiceDeleteParams{
		HTTPClient: client,
	}
}

/*
ExpectationServiceDeleteParams contains all the parameters to send to the API endpoint

	for the expectation service delete operation.

	Typically these are written to a http.Request.
*/
type ExpectationServiceDeleteParams struct {

	// Body.
	Body *models.ExpectationServiceDeleteRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the expectation service delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExpectationServiceDeleteParams) WithDefaults() *ExpectationServiceDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the expectation service delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExpectationServiceDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the expectation service delete params
func (o *ExpectationServiceDeleteParams) WithTimeout(timeout time.Duration) *ExpectationServiceDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the expectation service delete params
func (o *ExpectationServiceDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the expectation service delete params
func (o *ExpectationServiceDeleteParams) WithContext(ctx context.Context) *ExpectationServiceDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the expectation service delete params
func (o *ExpectationServiceDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the expectation service delete params
func (o *ExpectationServiceDeleteParams) WithHTTPClient(client *http.Client) *ExpectationServiceDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the expectation service delete params
func (o *ExpectationServiceDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the expectation service delete params
func (o *ExpectationServiceDeleteParams) WithBody(body *models.ExpectationServiceDeleteRequest) *ExpectationServiceDeleteParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the expectation service delete params
func (o *ExpectationServiceDeleteParams) SetBody(body *models.ExpectationServiceDeleteRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ExpectationServiceDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
