// Code generated by go-swagger; DO NOT EDIT.

package expectation_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/status-mok/server/e2e/app/http-client/models"
)

// ExpectationServiceDeleteReader is a Reader for the ExpectationServiceDelete structure.
type ExpectationServiceDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExpectationServiceDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewExpectationServiceDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewExpectationServiceDeleteDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewExpectationServiceDeleteOK creates a ExpectationServiceDeleteOK with default headers values
func NewExpectationServiceDeleteOK() *ExpectationServiceDeleteOK {
	return &ExpectationServiceDeleteOK{}
}

/*
ExpectationServiceDeleteOK describes a response with status code 200, with default header values.

A successful response.
*/
type ExpectationServiceDeleteOK struct {
	Payload *models.ExpectationServiceDeleteResponse
}

// IsSuccess returns true when this expectation service delete o k response has a 2xx status code
func (o *ExpectationServiceDeleteOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this expectation service delete o k response has a 3xx status code
func (o *ExpectationServiceDeleteOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this expectation service delete o k response has a 4xx status code
func (o *ExpectationServiceDeleteOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this expectation service delete o k response has a 5xx status code
func (o *ExpectationServiceDeleteOK) IsServerError() bool {
	return false
}

// IsCode returns true when this expectation service delete o k response a status code equal to that given
func (o *ExpectationServiceDeleteOK) IsCode(code int) bool {
	return code == 200
}

func (o *ExpectationServiceDeleteOK) Error() string {
	return fmt.Sprintf("[POST /expectation/delete][%d] expectationServiceDeleteOK  %+v", 200, o.Payload)
}

func (o *ExpectationServiceDeleteOK) String() string {
	return fmt.Sprintf("[POST /expectation/delete][%d] expectationServiceDeleteOK  %+v", 200, o.Payload)
}

func (o *ExpectationServiceDeleteOK) GetPayload() *models.ExpectationServiceDeleteResponse {
	return o.Payload
}

func (o *ExpectationServiceDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ExpectationServiceDeleteResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewExpectationServiceDeleteDefault creates a ExpectationServiceDeleteDefault with default headers values
func NewExpectationServiceDeleteDefault(code int) *ExpectationServiceDeleteDefault {
	return &ExpectationServiceDeleteDefault{
		_statusCode: code,
	}
}

/*
ExpectationServiceDeleteDefault describes a response with status code -1, with default header values.

ExpectationServiceDeleteDefault expectation service delete default
*/
type ExpectationServiceDeleteDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// Code gets the status code for the expectation service delete default response
func (o *ExpectationServiceDeleteDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this expectation service delete default response has a 2xx status code
func (o *ExpectationServiceDeleteDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this expectation service delete default response has a 3xx status code
func (o *ExpectationServiceDeleteDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this expectation service delete default response has a 4xx status code
func (o *ExpectationServiceDeleteDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this expectation service delete default response has a 5xx status code
func (o *ExpectationServiceDeleteDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this expectation service delete default response a status code equal to that given
func (o *ExpectationServiceDeleteDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ExpectationServiceDeleteDefault) Error() string {
	return fmt.Sprintf("[POST /expectation/delete][%d] ExpectationService_Delete default  %+v", o._statusCode, o.Payload)
}

func (o *ExpectationServiceDeleteDefault) String() string {
	return fmt.Sprintf("[POST /expectation/delete][%d] ExpectationService_Delete default  %+v", o._statusCode, o.Payload)
}

func (o *ExpectationServiceDeleteDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *ExpectationServiceDeleteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
